name: parser_builder_lite
description: Parser Builder Lite is a lightweight and uncomplicated parser builder.
version: 0.2.1
homepage: https://github.com/mezoni/parser_builder_lite
environment:
  sdk: '>=3.0.0 <4.0.0'
dev_dependencies:
  dart_style: ^2.2.4
  lints: ^2.0.0