name: parser_builder_lite
description: Parser Builder Lite is a lightweight and uncomplicated parser combinator builder (source code generator).
version: 0.7.0
homepage: https://github.com/mezoni/parser_builder_lite
topics:
  - parser
  - parser-builder
  - parser-combinator
  - parser-generator
  - peg
environment:
  sdk: '>=3.0.0 <4.0.0'
dev_dependencies:
  dart_style: ^2.3.2
  lints: ^2.1.1
  test: ^1.24.4