name: parser_builder_lite
description: Parser Builder Lite is a lightweight and uncomplicated parser combinator builder (source code generator).
version: 0.5.0
homepage: https://github.com/mezoni/parser_builder_lite
topics:
  - parser
  - peg
environment:
  sdk: '>=3.0.0 <4.0.0'
dev_dependencies:
  dart_style: ^2.2.4
  lints: ^2.0.0
  test: ^1.24.4