name: parser_builder_lite
description: Parser Builder Lite is a lightweight and uncomplicated parser combinator builder (source code generator).
version: 0.2.3
homepage: https://github.com/mezoni/parser_builder_lite
topics:
  - parser
  - parser_combinator
  - parser_generator
  - peg
environment:
  sdk: '>=3.0.0 <4.0.0'
dev_dependencies:
  dart_style: ^2.2.4
  lints: ^2.0.0